generic:
  configMaps:
    smarthome4-ui-config-map:
      MQTT_HOST: "mosquitto-service"
      MQTT_PORT: "1883"
      Z2M_TOPIC: "zigbee2mqtt"
      HA_BASE_URL: "http://homeassistant-service:8123"
      SMARTHOME_CORE_URL: "http://smarthome4-service:8080"
      CORS_ORIGINS: ""
      GITHUB_REPO: ""
      GITHUB_CONFIG_PATH: ""
      GITHUB_ALEXA_CONFIG_PATH: ""
      GITHUB_BRANCH: "main"
  externalSecrets:
    smarthome4-ui-secret:
      - HA_API_TOKEN: "/smarthome4/HOMEASSISTANT_APITOKEN"
      - MQTT_USERNAME: "/smarthome4/MQTT_BROKER_USERNAME"
      - MQTT_PASSWORD: "/smarthome4/MQTT_BROKER_PASSWORD"
      - GITHUB_TOKEN: "/smarthome4-ui/GITHUB_TOKEN"
  deployment:
    image: 629099703604.dkr.ecr.eu-central-1.amazonaws.com/hess.pm/smarthome4-ui:v0.0.10
    imagePullSecrets:
    - regcred-primary
    ports:
    - containerPort: 8000
    envFrom:
      configMapRef: smarthome4-ui-config-map
      secretRef: smarthome4-ui-secret
  service:
    ports:
    - name: http
      port: 8000
  ingress:
    https:
    - subdomain: lights
      port: 8000
      middlewares:
      - oauth2-proxy
