apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: {{ $.Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vaultwarden
    repoURL: https://guerzon.github.io/vaultwarden
    targetRevision: 0.34.6
    helm:
      valuesObject:
        image:
          # renovate: depName=vaultwarden/server
          tag: "1.35.4-alpine"
        domain: "https://vaultwarden.{{ $.Values.global.domain }}"
        signupsAllowed: false
        ingress:
          enabled: false

        storage:
          existingVolumeClaim:
            dataPath: "/data"
            attachmentsPath: "/data/attachments"
            claimName: "vaultwarden-data-pvc"

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi

        adminToken:
          existingSecret: "vaultwarden-secret"
          existingSecretKey: "ADMIN_TOKEN"

        smtp:
          host: "{{ .Values.smtp.host }}"
          from: "{{ .Values.smtp.from }}"
          fromName: "{{ .Values.smtp.fromName }}"
          existingSecret: "vaultwarden-smtp-secret"
          username:
            existingSecretKey: "SMTP_USERNAME"
          password:
            existingSecretKey: "SMTP_PASSWORD"

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $.Release.Namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
