apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plex-config
  namespace: {{ $.Release.Namespace }}
data:
  PUID: "1000"
  PGID: "997"
  TZ: "Europe/Berlin"
  HOSTNAME: "nudelkiste"
  VERSION: "docker"
  NVIDIA_VISIBLE_DEVICES: "all"
