apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarthome4-deployment
  namespace: {{ $.Release.Namespace }}
  labels:
    app: containous
    name: smarthome4-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: containous
      task: smarthome4-task
  template:
    metadata:
      labels:
        app: containous
        task: smarthome4-task
    spec:
      containers:
        - name: smarthome4
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: smarthome4-config-map
            - secretRef:
                name: smarthome4-secret

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
      imagePullSecrets:
        - name: regcred-primary