{{- if .Values.configMaps }}
  {{- range $cmName, $cmData := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  namespace: {{ $.Release.Namespace }}
data:
{{- toYaml $cmData | nindent 2 }}
  {{- end }}
{{- end }}
