apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: generic
  repository: file://../generic
  version: 0.1.30
- name: oauth2-proxy
  repository: https://oauth2-proxy.github.io/manifests
  version: 10.1.3
description: Helm chart for traefik
name: traefik
type: application
version: 0.1.0
