apiVersion: v1
kind: ConfigMap
metadata:
  name: smarthome4-ui-config-map
  namespace: {{ $.Release.Namespace }}
data:
  MQTT_HOST: {{ .Values.mqtt.host | quote }}
  MQTT_PORT: {{ .Values.mqtt.port | quote }}
  Z2M_TOPIC: {{ .Values.z2mTopic | quote }}
  HA_BASE_URL: {{ .Values.homeAssistant.baseUrl | quote }}
  CORS_ORIGINS: {{ .Values.corsOrigins | quote }}
