generic:
  appName: smarthome3
  configMaps:
    smarthome3-config-map:
      HUE_IP: "NOT_SET"
      MQTT_URL: "tcp://mosquitto-service:1883"
      HOME_ASSISTANT_IP: "homeassistant-service:8123"
      spring.profiles.active: "NOT_SET"
  externalSecrets:
    smarthome3-secret:
      - HUE_API_KEY: "/smarthome3/HUE_API_KEY"
      - HOME_ASSISTANT_TOKEN: "/smarthome3/HOME_ASSISTANT_TOKEN"
  deployment:
    image: 629099703604.dkr.ecr.eu-central-1.amazonaws.com/nudelkiste:1.2.1
    ports:
    - containerPort: 8080
    envFrom:
      configMapRef: smarthome3-config-map
      secretRef: smarthome3-secret
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 30
    imagePullSecrets:
    - regcred-primary
