generic:
  appName: smarthome3
  externalSecrets:
    smarthome3-secret:
      - HUE_API_KEY: "/smarthome3/HUE_API_KEY"
      - HOME_ASSISTANT_TOKEN: "/smarthome3/HOME_ASSISTANT_TOKEN"

# Container image configuration
image:
  repository: 629099703604.dkr.ecr.eu-central-1.amazonaws.com/nudelkiste
  tag: 1.2.1
  pullPolicy: Always

# Application configuration
hueIp: NOT_SET
mqttUrl: tcp://mosquitto-service:1883
homeAssistantIp: homeassistant-service:8123
profilesActive: NOT_SET
