configMapName: "alexa-smarthome-skill-config"
secretName: "alexa-smarthome-deploy-credentials"

skillId: ~
lambdaArn: ~
lambdaRegion: ~
homeAssistantUrl: ~

files:
  skillJson: ~

generic:
  externalSecrets:
    alexa-smarthome-deploy-credentials:
      - LWA_CLIENT_ID: /alexa-smarthome-skill/LWA_CLIENT_ID
      - LWA_CLIENT_SECRET: /alexa-smarthome-skill/LWA_CLIENT_SECRET
      - LWA_REFRESH_TOKEN: /alexa-smarthome-skill/LWA_REFRESH_TOKEN
      - AWS_ACCESS_KEY_ID: /alexa-smarthome-skill/AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY: /alexa-smarthome-skill/AWS_SECRET_ACCESS_KEY
